Install pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
# check the version
print(pd.__version__)

2.2.2

Creating a Series Data

In [ ]:
series1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(series1)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
# Creating manual indexes for series
series2 = pd.Series([1,2,3,4,5,6,7,8,9,10], index=['a','b','c','d','e','f','g','h','i','j'])
print(series2)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
# accesing data from the series
print(series1[0])

1

In [ ]:
print(series2['d'])

4

In [ ]:
print(series1.iloc[1])

2

In [ ]:
# accesing data in range
print(series1[0:5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# Creating an dataframe through Dictonary
data = {
 "Rahul":80,
 "Priya":90,
 "Aman":75
}

series3 = pd.Series(data)
print(series3)

Rahul    80
Priya    90
Aman     75
dtype: int64

In [ ]:
print(series3['Priya'])

90

In [ ]:
# getting indexs of series
print(series3.index)

Index(['Rahul', 'Priya', 'Aman'], dtype='object')

In [ ]:
# getting values
print(series3.values)

[80 90 75]

In [ ]:
# datatype
print(series3.dtype)

int64

In [ ]:
# size
print(series3.size)

3

Pandas DataFrame

In [ ]:
data = {
 "Name":["Rahul","Priya","Aman"],
 "Age":[20,21,19],
 "Marks":[85,91,78]
}
df = pd.DataFrame(data)

In [ ]:
print(df)

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     91
2   Aman   19     78

In [ ]:
import random

names = [f"Person {i+1}" for i in range(30)]
ages = [random.randint(18, 60) for _ in range(30)]
marks = [random.randint(50, 100) for _ in range(30)]

new_data = {
    "Name": names,
    "Age": ages,
    "Marks": marks
}

print(new_data)

{'Name': ['Person 1', 'Person 2', 'Person 3', 'Person 4', 'Person 5', 'Person 6', 'Person 7', 'Person 8', 'Person 9', 'Person 10', 'Person 11', 'Person 12', 'Person 13', 'Person 14', 'Person 15', 'Person 16', 'Person 17', 'Person 18', 'Person 19', 'Person 20', 'Person 21', 'Person 22', 'Person 23', 'Person 24', 'Person 25', 'Person 26', 'Person 27', 'Person 28', 'Person 29', 'Person 30'], 'Age': [53, 24, 39, 50, 40, 43, 18, 23, 39, 41, 42, 41, 48, 29, 20, 22, 36, 38, 44, 33, 18, 26, 44, 36, 28, 32, 41, 31, 52, 32], 'Marks': [70, 92, 83, 65, 69, 64, 63, 69, 88, 91, 98, 71, 71, 53, 93, 93, 66, 81, 97, 60, 94, 71, 55, 89, 51, 85, 65, 74, 53, 61]}

In [ ]:
df = pd.DataFrame(new_data)
print(df)

         Name  Age  Marks
0    Person 1   53     70
1    Person 2   24     92
2    Person 3   39     83
3    Person 4   50     65
4    Person 5   40     69
5    Person 6   43     64
6    Person 7   18     63
7    Person 8   23     69
8    Person 9   39     88
9   Person 10   41     91
10  Person 11   42     98
11  Person 12   41     71
12  Person 13   48     71
13  Person 14   29     53
14  Person 15   20     93
15  Person 16   22     93
16  Person 17   36     66
17  Person 18   38     81
18  Person 19   44     97
19  Person 20   33     60
20  Person 21   18     94
21  Person 22   26     71
22  Person 23   44     55
23  Person 24   36     89
24  Person 25   28     51
25  Person 26   32     85
26  Person 27   41     65
27  Person 28   31     74
28  Person 29   52     53
29  Person 30   32     61

In [ ]:
# accessing data in dataframe
df.head(7)

       Name  Age  Marks
0  Person 1   53     70
1  Person 2   24     92
2  Person 3   39     83
3  Person 4   50     65
4  Person 5   40     69
5  Person 6   43     64
6  Person 7   18     63

In [ ]:
df.tail(8)

         Name  Age  Marks
22  Person 23   44     55
23  Person 24   36     89
24  Person 25   28     51
25  Person 26   32     85
26  Person 27   41     65
27  Person 28   31     74
28  Person 29   52     53
29  Person 30   32     61

In [ ]:
df.sample(5)

         Name  Age  Marks
28  Person 29   52     53
1    Person 2   24     92
6    Person 7   18     63
17  Person 18   38     81
15  Person 16   22     93

In [ ]:
data = [
 ["Rahul",20,85],
 ["Priya",21,91],
 ["Aman",19,78]
]
df = pd.DataFrame(
 data,
 columns=["Name","Age","Marks"]
)

In [ ]:
df

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     91
2   Aman   19     78

In [ ]:
# columns
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
# index
print(df.index)

RangeIndex(start=0, stop=30, step=1)

In [ ]:
# size
print(df.size)

90

In [ ]:
# n dimensions
print(df.ndim)

2

In [ ]:
# accesing data though columns
df[["Name","Age"]]

         Name  Age
0    Person 1   53
1    Person 2   24
2    Person 3   39
3    Person 4   50
4    Person 5   40
5    Person 6   43
6    Person 7   18
7    Person 8   23
8    Person 9   39
9   Person 10   41
10  Person 11   42
11  Person 12   41
12  Person 13   48
13  Person 14   29
14  Person 15   20
15  Person 16   22
16  Person 17   36
17  Person 18   38
18  Person 19   44
19  Person 20   33
20  Person 21   18
21  Person 22   26
22  Person 23   44
23  Person 24   36
24  Person 25   28
25  Person 26   32
26  Person 27   41
27  Person 28   31
28  Person 29   52
29  Person 30   32

In [ ]:
# accesing data iloc
print(df.iloc[4])

Name     Person 5
Age            40
Marks          69
Name: 4, dtype: object

In [ ]:
# accesing data loc
print(df.loc[2:9])

        Name  Age  Marks
2   Person 3   39     83
3   Person 4   50     65
4   Person 5   40     69
5   Person 6   43     64
6   Person 7   18     63
7   Person 8   23     69
8   Person 9   39     88
9  Person 10   41     91