In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("shopping_trends.csv")

In [ ]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [ ]:
df.ndim

2

In [ ]:
df.shape

(3900, 19)

In [ ]:
df.size

74100

In [ ]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [ ]:
import numpy as np

# Identify numeric columns
numeric_cols = df.select_dtypes(include=np.number).columns

# Get 50 random indices
num_rows = len(df)
random_indices = np.random.choice(num_rows, 50, replace=False)

# Introduce 50 null entries into numeric columns
for col in numeric_cols:
    # For simplicity, we'll assign NaN to 50 random rows in each numeric column
    # A more precise way would be to ensure exactly 50 total nulls across all numeric columns combined
    # but for adding '50 null entries in the columns which are numeric', this is a direct interpretation.
    df.loc[random_indices, col] = np.nan

print("Null entries added to numeric columns.")

Null entries added to numeric columns.

In [ ]:
# Display the updated null counts
df.isnull().sum()

Customer ID                 50
Age                         50
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)       50
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Payment Method               0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases          50
Preferred Payment Method     0
Frequency of Purchases       0
dtype: int64

In [ ]:
df1 = df.copy()

In [ ]:
df1.isnull().sum()

Customer ID                 50
Age                         50
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)       50
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating               50
Subscription Status          0
Payment Method               0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases          50
Preferred Payment Method     0
Frequency of Purchases       0
dtype: int64

In [ ]:
df1.shape

(3850, 19)

In [ ]:
df1.dropna(inplace=True)

In [ ]:
df1.isnull().sum()

Customer ID                 50
Age                         50
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)       50
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Payment Method               0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases          50
Preferred Payment Method     0
Frequency of Purchases       0
dtype: int64

In [ ]:
df1['Review Rating'].fillna(0, inplace=True)

/tmp/ipykernel_688/4222580804.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Review Rating'].fillna(0, inplace=True)

In [ ]:
df1['Age'].fillna(df1['Age'].mean(), inplace=True)

/tmp/ipykernel_688/3226543192.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna(df1['Age'].mean(), inplace=True)

In [ ]:
df1['Age'].isnull().sum()

np.int64(0)

In [ ]:
df1.dropna(axis=1,inplace=True)

In [ ]:
df1.shape

(3850, 16)

In [ ]:
df1.isnull().sum()

Age                         0
Gender                      0
Item Purchased              0
Category                    0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [ ]:
df2 = df.copy()

In [ ]:
df2.isnull().sum()

Customer ID                 50
Age                         50
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)       50
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Payment Method               0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases          50
Preferred Payment Method     0
Frequency of Purchases       0
dtype: int64

In [ ]:
df2.dropna(subset=['Customer ID'], inplace=True)

In [ ]:
df2.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [ ]:
df3 = df.copy()

In [ ]:
df3.ffill(inplace=True)
df3.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [ ]:
df3.backfill(inplace=True)
df3.isnull().sum()

/tmp/ipykernel_688/476004108.py:1: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df3.backfill(inplace=True)

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [ ]:
df3.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1.0,55.0,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14.0,Venmo,Fortnightly
1,2.0,19.0,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2.0,Cash,Fortnightly
2,3.0,50.0,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23.0,Credit Card,Weekly
3,4.0,21.0,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49.0,PayPal,Weekly
4,5.0,45.0,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31.0,PayPal,Annually

In [ ]:
df[(df['Age'] ==19) & (df['Gender'] == 'Male')]
# !=
# <=
# >=
# <
# >

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
1,2.0,19.0,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2.0,Cash,Fortnightly
80,81.0,19.0,Male,Sandals,Footwear,72.0,New York,XL,Blue,Summer,3.3,Yes,Credit Card,Store Pickup,Yes,Yes,24.0,Credit Card,Every 3 Months
82,83.0,19.0,Male,Pants,Clothing,28.0,Georgia,S,Olive,Spring,4.0,Yes,Bank Transfer,2-Day Shipping,Yes,Yes,21.0,Credit Card,Every 3 Months
121,122.0,19.0,Male,Shorts,Clothing,72.0,Virginia,M,Olive,Winter,4.2,Yes,Cash,Standard,Yes,Yes,11.0,Cash,Fortnightly
144,145.0,19.0,Male,Shoes,Footwear,43.0,New Jersey,M,Silver,Fall,3.2,Yes,Credit Card,Express,Yes,Yes,25.0,Cash,Monthly
187,188.0,19.0,Male,Shoes,Footwear,94.0,Georgia,S,Purple,Spring,3.3,Yes,Credit Card,Store Pickup,Yes,Yes,1.0,Bank Transfer,Bi-Weekly
233,234.0,19.0,Male,Sweater,Clothing,83.0,Arizona,XL,Yellow,Fall,4.5,Yes,PayPal,Next Day Air,Yes,Yes,27.0,Bank Transfer,Every 3 Months
332,333.0,19.0,Male,Shirt,Clothing,86.0,New York,M,Maroon,Winter,2.8,Yes,Cash,2-Day Shipping,Yes,Yes,5.0,Credit Card,Monthly
403,404.0,19.0,Male,Sneakers,Footwear,45.0,Nevada,M,Orange,Winter,4.5,Yes,Credit Card,Next Day Air,Yes,Yes,12.0,Bank Transfer,Annually
446,447.0,19.0,Male,Shirt,Clothing,74.0,West Virginia,M,Silver,Summer,4.1,Yes,Bank Transfer,Store Pickup,Yes,Yes,15.0,Venmo,Monthly
467,468.0,19.0,Male,Backpack,Accessories,51.0,Nebraska,S,Orange,Spring,4.5,Yes,Credit Card,2-Day Shipping,Yes,Yes,37.0,Debit Card,Every 3 Months
512,513.0,19.0,Male,Gloves,Accessories,49.0,New York,L,Peach,Winter,3.3,Yes,Credit Card,Next Day Air,Yes,Yes,2.0,Bank Transfer,Monthly
577,578.0,19.0,Male,Skirt,Clothing,52.0,Alabama,M,Black,Fall,3.7,Yes,PayPal,Store Pickup,Yes,Yes,41.0,Venmo,Annually
619,620.0,19.0,Male,Backpack,Accessories,34.0,Nebraska,M,Charcoal,Summer,4.6,Yes,Debit Card,Store Pickup,Yes,Yes,1.0,Debit Card,Every 3 Months
623,624.0,19.0,Male,Shoes,Footwear,70.0,Nevada,M,White,Fall,4.7,Yes,Bank Transfer,Standard,Yes,Yes,48.0,PayPal,Bi-Weekly
687,688.0,19.0,Male,Gloves,Accessories,38.0,West Virginia,XL,Turquoise,Winter,3.3,Yes,Cash,Free Shipping,Yes,Yes,46.0,Bank Transfer,Quarterly
689,690.0,19.0,Male,Hoodie,Clothing,91.0,Pennsylvania,M,Orange,Summer,4.7,Yes,Cash,Express,Yes,Yes,35.0,Credit Card,Every 3 Months
770,771.0,19.0,Male,Sneakers,Footwear,54.0,Vermont,M,Gray,Spring,3.3,Yes,Venmo,Express,Yes,Yes,8.0,Credit Card,Annually
858,859.0,19.0,Male,Jacket,Outerwear,26.0,Oklahoma,L,Olive,Fall,3.1,Yes,PayPal,Free Shipping,Yes,Yes,33.0,PayPal,Weekly
862,863.0,19.0,Male,Coat,Outerwear,84.0,Arkansas,M,Charcoal,Winter,4.9,Yes,PayPal,Standard,Yes,Yes,13.0,PayPal,Fortnightly
886,887.0,19.0,Male,Shorts,Clothing,54.0,Utah,S,Brown,Summer,3.6,Yes,PayPal,Express,Yes,Yes,48.0,Bank Transfer,Monthly
1033,1034.0,19.0,Male,Pants,Clothing,52.0,Montana,S,Silver,Spring,4.6,Yes,Credit Card,Free Shipping,Yes,Yes,41.0,Bank Transfer,Quarterly
1095,1096.0,19.0,Male,Coat,Outerwear,34.0,Tennessee,S,Peach,Summer,3.0,No,Debit Card,Free Shipping,Yes,Yes,30.0,Bank Transfer,Quarterly
1099,1100.0,19.0,Male,Sweater,Clothing,73.0,North Carolina,M,Peach,Fall,2.6,No,Cash,Next Day Air,Yes,Yes,45.0,Bank Transfer,Fortnightly
1219,1220.0,19.0,Male,Sweater,Clothing,23.0,Vermont,M,Gold,Winter,2.5,No,Bank Transfer,Next Day Air,Yes,Yes,35.0,Credit Card,Bi-Weekly
1277,1278.0,19.0,Male,Blouse,Clothing,97.0,Rhode Island,L,Green,Spring,5.0,No,Debit Card,Express,Yes,Yes,5.0,Venmo,Quarterly
1348,1349.0,19.0,Male,Belt,Accessories,54.0,Nebraska,XL,Purple,Spring,3.2,No,PayPal,Standard,Yes,Yes,23.0,Credit Card,Fortnightly
1358,1359.0,19.0,Male,Scarf,Accessories,22.0,Nebraska,XL,Pink,Spring,2.5,No,Debit Card,Store Pickup,Yes,Yes,25.0,Venmo,Every 3 Months
1399,1400.0,19.0,Male,Hat,Accessories,81.0,Nebraska,M,Olive,Winter,3.1,No,Bank Transfer,Store Pickup,Yes,Yes,48.0,Venmo,Annually
1499,1500.0,19.0,Male,Boots,Footwear,85.0,Georgia,S,Olive,Fall,3.4,No,Cash,Free Shipping,Yes,Yes,24.0,Credit Card,Every 3 Months
1549,1550.0,19.0,Male,Sneakers,Footwear,55.0,Kansas,M,Black,Spring,2.9,No,Cash,2-Day Shipping,Yes,Yes,19.0,Debit Card,Every 3 Months
1664,1665.0,19.0,Male,Handbag,Accessories,53.0,Minnesota,M,Purple,Spring,5.0,No,PayPal,Next Day Air,Yes,Yes,35.0,PayPal,Weekly
1710,1711.0,19.0,Male,Pants,Clothing,59.0,Arkansas,XL,Orange,Fall,3.8,No,Debit Card,Store Pickup,No,No,7.0,Credit Card,Quarterly
1757,1758.0,19.0,Male,Dress,Clothing,94.0,Michigan,L,Yellow,Fall,3.6,No,Bank Transfer,Standard,No,No,48.0,Debit Card,Annually
1820,1821.0,19.0,Male,Shirt,Clothing,94.0,Washington,XL,Gold,Fall,5.0,No,PayPal,Express,No,No,31.0,PayPal,Monthly
1848,1849.0,19.0,Male,Jeans,Clothing,73.0,Maine,XL,Yellow,Winter,2.7,No,Credit Card,Express,No,No,34.0,Cash,Every 3 Months
1864,1865.0,19.0,Male,Backpack,Accessories,72.0,Wyoming,S,Cyan,Fall,3.2,No,Bank Transfer,2-Day Shipping,No,No,21.0,Venmo,Quarterly
1935,1936.0,19.0,Male,Blouse,Clothing,68.0,North Carolina,XL,Violet,Spring,4.8,No,Debit Card,Free Shipping,No,No,45.0,Cash,Fortnightly
2042,2043.0,19.0,Male,Shoes,Footwear,52.0,Alabama,M,Red,Spring,4.0,No,Credit Card,2-Day Shipping,No,No,35.0,Venmo,Monthly
2053,2054.0,19.0,Male,Sunglasses,Accessories,60.0,Wyoming,S,Purple,Spring,4.5,No,Bank Transfer,2-Day Shipping,No,No,16.0,Credit Card,Fortnightly
2131,2132.0,19.0,Male,Shorts,Clothing,52.0,Montana,M,Red,Fall,3.6,No,Credit Card,Express,No,No,9.0,Bank Transfer,Fortnightly
2148,2149.0,19.0,Male,T-shirt,Clothing,45.0,Nebraska,XL,Turquoise,Winter,4.6,No,PayPal,2-Day Shipping,No,No,19.0,PayPal,Bi-Weekly
2158,2159.0,19.0,Male,Gloves,Accessories,84.0,Massachusetts,XL,Olive,Spring,4.6,No,Credit Card,Standard,No,No,9.0,Bank Transfer,Fortnightly
2220,2221.0,19.0,Male,Belt,Accessories,62.0,Wyoming,XL,Beige,Fall,4.5,No,Cash,Store Pickup,No,No,47.0,Cash,Annually
2312,2313.0,19.0,Male,T-shirt,Clothing,30.0,Vermont,L,Violet,Summer,3.7,No,PayPal,Free Shipping,No,No,19.0,Cash,Every 3 Months
2336,2337.0,19.0,Male,Belt,Accessories,94.0,California,M,Green,Winter,3.1,No,Cash,Free Shipping,No,No,11.0,Credit Card,Weekly
2359,2360.0,19.0,Male,Scarf,Accessories,81.0,Pennsylvania,S,Gold,Spring,3.3,No,Venmo,2-Day Shipping,No,No,44.0,Bank Transfer,Every 3 Months
2386,2387.0,19.0,Male,Socks,Clothing,33.0,Illinois,L,Blue,Summer,2.9,No,Credit Card,Standard,No,No,14.0,Venmo,Monthly
2509,2510.0,19.0,Male,Socks,Clothing,48.0,Washington,M,Black,Spring,4.4,No,PayPal,Free Shipping,No,No,9.0,Bank Transfer,Quarterly
2527,2528.0,19.0,Male,Pants,Clothing,36.0,Illinois,M,Gold,Fall,3.6,No,Cash,Express,No,No,33.0,Bank Transfer,Every 3 Months
2567,2568.0,19.0,Male,Sunglasses,Accessories,25.0,Michigan,XL,Gold,Spring,4.3,No,Venmo,Store Pickup,No,No,24.0,Cash,Fortnightly
2582,2583.0,19.0,Male,Dress,Clothing,98.0,South Dakota,S,Indigo,Fall,3.6,No,Venmo,2-Day Shipping,No,No,4.0,Venmo,Every 3 Months
2624,2625.0,19.0,Male,Dress,Clothing,59.0,South Dakota,M,Indigo,Summer,3.3,No,Debit Card,Standard,No,No,19.0,Credit Card,Annually

In [ ]:
df[(df['Size']=='S') | (df['Size']=='M')]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Payment Method, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Preferred Payment Method, Frequency of Purchases]
Index: []

In [ ]:
df[df['Color'].isin(["Yellow","Silver","Green","Orange"])]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
8,9.0,26.0,Male,Coat,Outerwear,97.0,West Virginia,L,Silver,Summer,2.6,Yes,Venmo,Express,Yes,Yes,8.0,Venmo,Annually
19,20.0,66.0,Male,Pants,Clothing,90.0,Rhode Island,M,Green,Summer,3.3,Yes,Venmo,Standard,Yes,Yes,46.0,Debit Card,Bi-Weekly
24,25.0,18.0,Male,Jacket,Outerwear,22.0,Florida,M,Green,Fall,2.9,Yes,Cash,Store Pickup,Yes,Yes,16.0,Debit Card,Weekly
25,26.0,18.0,Male,Hoodie,Clothing,25.0,Texas,M,Silver,Summer,3.6,Yes,Bank Transfer,Express,Yes,Yes,14.0,PayPal,Annually
32,33.0,36.0,Male,Jacket,Outerwear,67.0,Kansas,M,Silver,Summer,4.9,Yes,Bank Transfer,Free Shipping,Yes,Yes,37.0,Venmo,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3873,3874.0,42.0,Female,Sandals,Footwear,43.0,Louisiana,L,Silver,Summer,4.0,No,PayPal,Standard,No,No,22.0,Credit Card,Weekly
3881,3882.0,56.0,Female,Scarf,Accessories,25.0,Georgia,L,Silver,Spring,2.8,No,PayPal,2-Day Shipping,No,No,17.0,Debit Card,Weekly
3889,3890.0,57.0,Female,Dress,Clothing,65.0,Alaska,S,Yellow,Spring,3.5,No,Debit Card,Express,No,No,49.0,Bank Transfer,Annually
3890,3891.0,35.0,Female,Shirt,Clothing,81.0,Nebraska,XL,Green,Winter,2.6,No,Credit Card,Standard,No,No,33.0,Debit Card,Annually
3897,3898.0,46.0,Female,Belt,Accessories,33.0,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24.0,Venmo,Quarterly

In [ ]:
df['Age']

0       55.0
1       19.0
2       50.0
3       21.0
4       45.0
        ...
3895    40.0
3896    52.0
3897    46.0
3898    44.0
3899    52.0
Name: Age, Length: 3850, dtype: float64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Payment Method',
       'Shipping Type', 'Discount Applied', 'Promo Code Used',
       'Previous Purchases', 'Preferred Payment Method',
       'Frequency of Purchases'],
      dtype='object')

Sorting

In [ ]:
df.sort_values(by="Purchase Amount (USD)")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
3854,3855.0,57.0,Female,T-shirt,Clothing,20.0,Florida,M,Black,Spring,4.2,No,Venmo,Free Shipping,No,No,4.0,Venmo,Annually
26,27.0,38.0,Male,Jewelry,Accessories,20.0,Nevada,M,Red,Spring,3.6,Yes,Cash,Next Day Air,Yes,Yes,13.0,Credit Card,Annually
3880,3881.0,42.0,Female,Shirt,Clothing,20.0,Massachusetts,M,Red,Winter,3.9,No,Credit Card,Free Shipping,No,No,40.0,PayPal,Monthly
2561,2562.0,32.0,Male,Hoodie,Clothing,20.0,New York,L,Magenta,Spring,2.7,No,Credit Card,Free Shipping,No,No,22.0,Debit Card,Quarterly
3793,3794.0,62.0,Female,Sunglasses,Accessories,20.0,Delaware,M,Pink,Fall,4.0,No,Cash,Standard,No,No,46.0,Bank Transfer,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2430,2431.0,20.0,Male,Jacket,Outerwear,100.0,North Dakota,XL,White,Summer,4.3,No,Cash,Express,No,No,42.0,Cash,Quarterly
518,519.0,24.0,Male,Blouse,Clothing,100.0,Oregon,M,Beige,Fall,2.9,Yes,PayPal,Next Day Air,Yes,Yes,16.0,Venmo,Every 3 Months
861,862.0,46.0,Male,Skirt,Clothing,100.0,Virginia,XL,Green,Spring,3.3,Yes,PayPal,2-Day Shipping,Yes,Yes,35.0,Credit Card,Every 3 Months
2958,2959.0,55.0,Female,Skirt,Clothing,100.0,Ohio,M,Black,Summer,4.5,No,Venmo,Standard,No,No,28.0,PayPal,Monthly
1456,1457.0,59.0,Male,Coat,Outerwear,100.0,Montana,S,Olive,Spring,2.7,No,Venmo,Store Pickup,Yes,Yes,30.0,PayPal,Every 3 Months

In [ ]:
df.sort_values(by="Purchase Amount (USD)", ascending=False)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
518,519.0,24.0,Male,Blouse,Clothing,100.0,Oregon,M,Beige,Fall,2.9,Yes,PayPal,Next Day Air,Yes,Yes,16.0,Venmo,Every 3 Months
95,96.0,37.0,Male,Sneakers,Footwear,100.0,Missouri,L,Pink,Fall,3.8,Yes,PayPal,Free Shipping,Yes,Yes,48.0,PayPal,Monthly
2802,2803.0,22.0,Female,Coat,Outerwear,100.0,Hawaii,L,Red,Fall,3.1,No,Bank Transfer,Store Pickup,No,No,42.0,Credit Card,Fortnightly
1405,1406.0,33.0,Male,Socks,Clothing,100.0,New Hampshire,M,Peach,Winter,2.7,No,Cash,Store Pickup,Yes,Yes,39.0,Credit Card,Monthly
3725,3726.0,18.0,Female,Dress,Clothing,100.0,Oklahoma,S,Turquoise,Winter,4.4,No,Bank Transfer,Next Day Air,No,No,2.0,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2301,2302.0,37.0,Male,Pants,Clothing,20.0,Maine,L,Turquoise,Winter,2.9,No,Debit Card,Next Day Air,No,No,21.0,Debit Card,Annually
3083,3084.0,22.0,Female,Pants,Clothing,20.0,Illinois,S,Purple,Summer,3.5,No,Venmo,Store Pickup,No,No,28.0,PayPal,Quarterly
3854,3855.0,57.0,Female,T-shirt,Clothing,20.0,Florida,M,Black,Spring,4.2,No,Venmo,Free Shipping,No,No,4.0,Venmo,Annually
508,509.0,27.0,Male,Jewelry,Accessories,20.0,Illinois,S,Yellow,Winter,3.7,Yes,Cash,Store Pickup,Yes,Yes,31.0,PayPal,Quarterly
5,6.0,46.0,Male,Sneakers,Footwear,20.0,Wyoming,M,White,Summer,2.9,Yes,Venmo,Standard,Yes,Yes,14.0,Venmo,Weekly

In [ ]:
df.sort_values(by="Category",inplace=True)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
3899,3900.0,52.0,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33.0,Venmo,Quarterly
197,198.0,59.0,Male,Scarf,Accessories,78.0,South Carolina,M,Black,Fall,3.2,Yes,Debit Card,2-Day Shipping,Yes,Yes,41.0,Credit Card,Monthly
198,199.0,57.0,Male,Jewelry,Accessories,45.0,Utah,M,Turquoise,Winter,4.8,Yes,Cash,Standard,Yes,Yes,39.0,Credit Card,Fortnightly
199,200.0,54.0,Male,Hat,Accessories,73.0,Idaho,XL,Green,Summer,3.8,Yes,Debit Card,Express,Yes,Yes,32.0,Cash,Weekly
2000,2001.0,26.0,Male,Belt,Accessories,27.0,California,M,Lavender,Winter,3.6,No,Venmo,2-Day Shipping,No,No,25.0,Cash,Bi-Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2341,2342.0,56.0,Male,Jacket,Outerwear,31.0,Connecticut,L,Teal,Summer,4.5,No,Cash,Express,No,No,22.0,Venmo,Every 3 Months
3337,3338.0,23.0,Female,Jacket,Outerwear,23.0,Arizona,L,Blue,Winter,4.4,No,Bank Transfer,2-Day Shipping,No,No,45.0,Bank Transfer,Bi-Weekly
84,85.0,52.0,Male,Coat,Outerwear,32.0,Arizona,S,Peach,Spring,4.4,Yes,Cash,Standard,Yes,Yes,42.0,Bank Transfer,Every 3 Months
1424,1425.0,66.0,Male,Jacket,Outerwear,23.0,Connecticut,S,Indigo,Fall,3.5,No,Cash,Standard,Yes,Yes,34.0,Bank Transfer,Every 3 Months
3293,3294.0,19.0,Female,Coat,Outerwear,91.0,West Virginia,M,Gold,Spring,3.5,No,Bank Transfer,2-Day Shipping,No,No,47.0,Credit Card,Fortnightly

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
3899,3900.0,52.0,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33.0,Venmo,Quarterly
954,955.0,60.0,Male,Hat,Accessories,74.0,Louisiana,S,Turquoise,Fall,3.5,Yes,Venmo,Standard,Yes,Yes,18.0,Credit Card,Every 3 Months
953,954.0,68.0,Male,Sunglasses,Accessories,50.0,Utah,S,Cyan,Spring,3.6,Yes,Credit Card,2-Day Shipping,Yes,Yes,36.0,Venmo,Quarterly
952,953.0,36.0,Male,Hat,Accessories,71.0,Idaho,S,Red,Fall,3.1,Yes,Bank Transfer,2-Day Shipping,Yes,Yes,28.0,PayPal,Monthly
3063,3064.0,26.0,Female,Sunglasses,Accessories,43.0,Connecticut,L,Brown,Winter,3.9,No,Debit Card,Store Pickup,No,No,24.0,Credit Card,Fortnightly

In [ ]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
3418,3419.0,53.0,Female,Jacket,Outerwear,30.0,South Carolina,M,Beige,Summer,2.8,No,Cash,Free Shipping,No,No,35.0,Debit Card,Annually
2549,2550.0,41.0,Male,Jacket,Outerwear,60.0,Virginia,M,Red,Fall,2.7,No,Credit Card,Standard,No,No,11.0,Debit Card,Every 3 Months
3641,3642.0,51.0,Female,Jacket,Outerwear,45.0,New York,M,Cyan,Fall,2.7,No,Debit Card,Free Shipping,No,No,39.0,Bank Transfer,Every 3 Months
832,833.0,58.0,Male,Jacket,Outerwear,80.0,California,L,Blue,Fall,2.5,Yes,Credit Card,Express,Yes,Yes,28.0,Cash,Bi-Weekly
3293,3294.0,19.0,Female,Coat,Outerwear,91.0,West Virginia,M,Gold,Spring,3.5,No,Bank Transfer,2-Day Shipping,No,No,47.0,Credit Card,Fortnightly

In [ ]:
df.reset_index(inplace=True,drop=True)

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,3900.0,52.0,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33.0,Venmo,Quarterly
1,955.0,60.0,Male,Hat,Accessories,74.0,Louisiana,S,Turquoise,Fall,3.5,Yes,Venmo,Standard,Yes,Yes,18.0,Credit Card,Every 3 Months
2,954.0,68.0,Male,Sunglasses,Accessories,50.0,Utah,S,Cyan,Spring,3.6,Yes,Credit Card,2-Day Shipping,Yes,Yes,36.0,Venmo,Quarterly
3,953.0,36.0,Male,Hat,Accessories,71.0,Idaho,S,Red,Fall,3.1,Yes,Bank Transfer,2-Day Shipping,Yes,Yes,28.0,PayPal,Monthly
4,3064.0,26.0,Female,Sunglasses,Accessories,43.0,Connecticut,L,Brown,Winter,3.9,No,Debit Card,Store Pickup,No,No,24.0,Credit Card,Fortnightly

In [ ]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,3900.0,52.0,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33.0,Venmo,Quarterly
1,955.0,60.0,Male,Hat,Accessories,74.0,Louisiana,S,Turquoise,Fall,3.5,Yes,Venmo,Standard,Yes,Yes,18.0,Credit Card,Every 3 Months
2,954.0,68.0,Male,Sunglasses,Accessories,50.0,Utah,S,Cyan,Spring,3.6,Yes,Credit Card,2-Day Shipping,Yes,Yes,36.0,Venmo,Quarterly
3,953.0,36.0,Male,Hat,Accessories,71.0,Idaho,S,Red,Fall,3.1,Yes,Bank Transfer,2-Day Shipping,Yes,Yes,28.0,PayPal,Monthly
4,3064.0,26.0,Female,Sunglasses,Accessories,43.0,Connecticut,L,Brown,Winter,3.9,No,Debit Card,Store Pickup,No,No,24.0,Credit Card,Fortnightly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,3419.0,53.0,Female,Jacket,Outerwear,30.0,South Carolina,M,Beige,Summer,2.8,No,Cash,Free Shipping,No,No,35.0,Debit Card,Annually
3796,2550.0,41.0,Male,Jacket,Outerwear,60.0,Virginia,M,Red,Fall,2.7,No,Credit Card,Standard,No,No,11.0,Debit Card,Every 3 Months
3797,3642.0,51.0,Female,Jacket,Outerwear,45.0,New York,M,Cyan,Fall,2.7,No,Debit Card,Free Shipping,No,No,39.0,Bank Transfer,Every 3 Months
3798,833.0,58.0,Male,Jacket,Outerwear,80.0,California,L,Blue,Fall,2.5,Yes,Credit Card,Express,Yes,Yes,28.0,Cash,Bi-Weekly
3799,3294.0,19.0,Female,Coat,Outerwear,91.0,West Virginia,M,Gold,Spring,3.5,No,Bank Transfer,2-Day Shipping,No,No,47.0,Credit Card,Fortnightly

In [ ]:
df.to_csv("data1.csv")