In [ ]:
import pandas as pd

In [ ]:
data = {
 "Employee":["Amit","Rahul","Priya","Neha","Karan","Anjali","Rohit","Sneha"],
 "Department":["IT","HR","IT","HR","Sales","Sales","IT","HR"],
 "City":["Mumbai","Delhi","Mumbai","Delhi","Pune","Pune","Delhi","Mumbai"],
 "Salary":[70000,50000,80000,55000,45000,48000,75000,60000],
 "Experience":[5,2,6,3,2,4,5,7]
}

In [ ]:
print(data)

{'Employee': ['Amit', 'Rahul', 'Priya', 'Neha', 'Karan', 'Anjali', 'Rohit', 'Sneha'], 'Department': ['IT', 'HR', 'IT', 'HR', 'Sales', 'Sales', 'IT', 'HR'], 'City': ['Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Pune', 'Pune', 'Delhi', 'Mumbai'], 'Salary': [70000, 50000, 80000, 55000, 45000, 48000, 75000, 60000], 'Experience': [5, 2, 6, 3, 2, 4, 5, 7]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.head()

  Employee Department    City  Salary  Experience
0     Amit         IT  Mumbai   70000           5
1    Rahul         HR   Delhi   50000           2
2    Priya         IT  Mumbai   80000           6
3     Neha         HR   Delhi   55000           3
4    Karan      Sales    Pune   45000           2

In [ ]:
df.columns

Index(['Employee', 'Department', 'City', 'Salary', 'Experience'], dtype='object')

In [ ]:
df.size

40

In [ ]:
df.shape

(8, 5)

df.groupby("Column_Name")

In [ ]:
cityDf = df.groupby('City')

In [ ]:
cityDf.groups

{'Delhi': [1, 3, 6], 'Mumbai': [0, 2, 7], 'Pune': [4, 5]}

**Syntax for iterating over the group:** for department, data in df.groupby("Department"):
 print(department)
 print(data)

In [ ]:
for city,data in df.groupby("City") :
  print(city)
  print(data)

Delhi
  Employee Department   City  Salary  Experience
1    Rahul         HR  Delhi   50000           2
3     Neha         HR  Delhi   55000           3
6    Rohit         IT  Delhi   75000           5
Mumbai
  Employee Department    City  Salary  Experience
0     Amit         IT  Mumbai   70000           5
2    Priya         IT  Mumbai   80000           6
7    Sneha         HR  Mumbai   60000           7
Pune
  Employee Department  City  Salary  Experience
4    Karan      Sales  Pune   45000           2
5   Anjali      Sales  Pune   48000           4

Grouping with department

In [ ]:
for department,data in df.groupby("Department") :
  print(department)
  print(data)

HR
  Employee Department    City  Salary  Experience
1    Rahul         HR   Delhi   50000           2
3     Neha         HR   Delhi   55000           3
7    Sneha         HR  Mumbai   60000           7
IT
  Employee Department    City  Salary  Experience
0     Amit         IT  Mumbai   70000           5
2    Priya         IT  Mumbai   80000           6
6    Rohit         IT   Delhi   75000           5
Sales
  Employee Department  City  Salary  Experience
4    Karan      Sales  Pune   45000           2
5   Anjali      Sales  Pune   48000           4

In [ ]:
cityDf.group_keys

True

Common aggregation functions include:
● sum()
● mean()
● max()
● min()
● count()
● size()
● median()
● std()
● var()
● first()
● last()

df.groupby("GroupColumn")["AggregateColumn"].aggregation_fun()

In [ ]:
df.groupby("Department")["Salary"].sum()

Department
HR       165000
IT       225000
Sales     93000
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].min()

Department
HR       50000
IT       70000
Sales    45000
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].max()

Department
HR       60000
IT       80000
Sales    48000
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].size()

Department
HR       3
IT       3
Sales    2
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].count()

Department
HR       3
IT       3
Sales    2
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].mean()

Department
HR       55000.0
IT       75000.0
Sales    46500.0
Name: Salary, dtype: float64

In [ ]:
df.groupby("Department")["Salary"].std()

Department
HR       5000.000000
IT       5000.000000
Sales    2121.320344
Name: Salary, dtype: float64

In [ ]:
df.groupby("Department")["Salary"].var()

Department
HR       25000000.0
IT       25000000.0
Sales     4500000.0
Name: Salary, dtype: float64

Multiple Aggregations
df.groupby("Department")["Salary"].agg(["sum","mean","min","max"])

In [ ]:
df.groupby("Department")["Salary"].agg(["min","max","mean","sum","var"])

              min    max     mean     sum         var
Department
HR          50000  60000  55000.0  165000  25000000.0
IT          70000  80000  75000.0  225000  25000000.0
Sales       45000  48000  46500.0   93000   4500000.0

Custom Column Names
df.groupby("Department").agg(
 Total_Salary=("Salary","sum"),
 Average_Salary=("Salary","mean"),
 Highest_Salary=("Salary","max")
)

In [ ]:
df.groupby("Department").agg(
    Minimum_Salary=("Salary","min"),
    Maximum_Salary=("Salary","max"),
    Average_Salary=("Salary","mean"),
    Total_Salary=("Salary","sum")
)

            Minimum_Salary  Maximum_Salary  Average_Salary  Total_Salary
Department
HR                   50000           60000         55000.0        165000
IT                   70000           80000         75000.0        225000
Sales                45000           48000         46500.0         93000

In [ ]:
df.groupby("Department").agg(
    Minimum_Experience=("Experience","min"),
    Maximum_Experience=("Experience","max"),
    Average_Experience=("Experience","mean"),
    Total_Experience=("Experience","sum")
)

,Minimum_Experience,Maximum_Experience,Average_Experience,Total_Experience
Department,,,,
HR,2,7,4.000000,12
IT,5,6,5.333333,16
Sales,2,4,3.000000,6

Groupoing Multiple Columns

In [ ]:
df.groupby(["Department","City"])["Salary"].sum()

Department  City
HR          Delhi     105000
            Mumbai     60000
IT          Delhi      75000
            Mumbai    150000
Sales       Pune       93000
Name: Salary, dtype: int64

In [ ]:
df.groupby(["Department","City"])["Salary"].agg(["sum","min"])

                      sum    min
Department City
HR         Delhi   105000  50000
           Mumbai   60000  60000
IT         Delhi    75000  75000
           Mumbai  150000  70000
Sales      Pune     93000  45000

Selecting Multiple Columns
df.groupby("Department")[["Salary","Experience"]].mean()

In [ ]:
df.groupby("City")[["Salary","Experience"]].mean()

         Salary  Experience
City
Delhi   60000.0    3.333333
Mumbai  70000.0    6.000000
Pune    46500.0    3.000000

In [ ]:
df.groupby("City")[["Salary","Experience"]].agg(["sum","min","max"])

        Salary               Experience
           sum    min    max        sum min max
City
Delhi   180000  50000  75000         10   2   5
Mumbai  210000  60000  80000         18   5   7
Pune     93000  45000  48000          6   2   4

Filtering Groups

df.groupby("Department").filter(
 lambda x: x["Salary"].mean() > 50000
)

In [ ]:
df.groupby("City").filter(lambda x: x["Salary"].min() > 50000)

  Employee Department    City  Salary  Experience
0     Amit         IT  Mumbai   70000           5
2    Priya         IT  Mumbai   80000           6
7    Sneha         HR  Mumbai   60000           7

In [ ]:
df.groupby("City").filter(lambda x: x["Experience"].min() > 3)

  Employee Department    City  Salary  Experience
0     Amit         IT  Mumbai   70000           5
2    Priya         IT  Mumbai   80000           6
7    Sneha         HR  Mumbai   60000           7

Transform

In [ ]:
df["Average Salary"] = df.groupby("Department")["Salary"].transform("mean")

In [ ]:
df.head()

  Employee Department    City  Salary  Experience  Average Salary
0     Amit         IT  Mumbai   70000           5         75000.0
1    Rahul         HR   Delhi   50000           2         55000.0
2    Priya         IT  Mumbai   80000           6         75000.0
3     Neha         HR   Delhi   55000           3         55000.0
4    Karan      Sales    Pune   45000           2         46500.0

In [ ]:
df["Min Salary"] = df.groupby("Department")["Salary"].transform("min")

In [ ]:
df.head()

  Employee Department    City  Salary  Experience  Average Salary  Min Salary
0     Amit         IT  Mumbai   70000           5         75000.0       70000
1    Rahul         HR   Delhi   50000           2         55000.0       50000
2    Priya         IT  Mumbai   80000           6         75000.0       70000
3     Neha         HR   Delhi   55000           3         55000.0       50000
4    Karan      Sales    Pune   45000           2         46500.0       45000

Sorting Grouped Results
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

In [ ]:
df.groupby("Department")["Salary"].sum().sort_values(ascending=False)

Department
IT       225000
HR       165000
Sales     93000
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].sum().sort_values(ascending=True)

Department
Sales     93000
HR       165000
IT       225000
Name: Salary, dtype: int64

In [ ]:
result = df.groupby("Department")["Salary"].sum().reset_index()

In [ ]:
result

  Department  Salary
0         HR  165000
1         IT  225000
2      Sales   93000